blueprint:
  name: Hue Smart button
  description: >
    HA version 2023.08 or newer

    Works with all functions

    Correct the problem of "short release" triggered on the same time as "long release"

    If multible switches needing the same functionality, select multiple
    Modified for Smart Button, based on:
    * https://community.home-assistant.io/t/philips-hue-friends-of-hue-switch-4-buttons-for-hue-integration/499450/32
    * https://gist.github.com/mertodinlo/a05b0b02aed0eaab07806a250aaf9c20

  domain: automation
  input:
    hue-switch-button1:
      name: "Hue Switch button 1"
      description: "Upper Left"
      selector:
        entity:
          device_class: button
          multiple: true 
    button_1_short_release:
      name: Short Release 1
      description: Action to run on button upper-left short release
      default: []
      selector:
        action: {}
        
    button_1_long_release:
      name: Long Release 1
      description: Action to run on button upper-left long release
      default: []
      selector:
        action: {}

    button_1_press:
      name: Press 1
      description: Action to run on button upper-left initial press
      default: []
      selector:
        action: {}

    button_1_repeat:
      name: Repeat 1
      description: Action to run on button upper-left repeat
      default: []
      selector:
        action: {}

mode: queued
max: 10

trigger:
- platform: state
  entity_id: !input 'hue-switch-button1'
  id: B1

action:
- variables:
    switch_to_state: '{{ trigger.to_state.attributes.event_type }}'
    switch_from_state: '{{ trigger.from_state.attributes.event_type }}'
    switch_id: '{{ trigger.id }}'
    #    switch_from_ID: '{{ trigger.entity_id }}'
- choose:
  - conditions: '{{ switch_to_state == ''initial_press'' }}'
    sequence:
    - choose:
      - conditions: '{{ switch_id == ''B1'' }}'
        sequence: !input 'button_1_press'

  - conditions: '{{ switch_to_state == ''repeat'' }}'
    sequence:
    - choose:
      - conditions: '{{ switch_id == ''B1'' }}'
        sequence: !input 'button_1_repeat'

  - conditions: '{{ switch_to_state == ''long_release'' }}'
    sequence:
    - choose:
      - conditions: '{{ switch_id == ''B1'' }}'
        sequence: !input 'button_1_long_release'

  - conditions: '{{ switch_to_state == ''short_release'' }}'
    sequence:
    - choose:
      - conditions: '{{ switch_from_state == ''initial_press'' }}'
        sequence: 
          - choose:
            - conditions: '{{ switch_id == ''B1'' }}'
              sequence: !input 'button_1_short_release'
